# Generated by Django 2.0.1 on 2018-02-12 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_openehr', '0006_auto_20180212_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferOfCareSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinical_synopsis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_openehr.ClinicalSynopsis')),
            ],
        ),
    ]
